### ISSUE TITLE
AttributeError: 'layout_coco_bert' object has no attribute 'render_indices_as_output'

### ISSUE THREAD

**Issue by ryomawaseda** [VickiCui/Loire#2]
When trying to generate sample layouts through layout_demo.py, I got an error below.
```
Traceback (most recent call last):
  File "./tools/layout_demo.py", line 38, in <module>
    layout_demo(config)
  File "./tools/layout_demo.py", line 24, in layout_demo
    trainer.sample_demo(input_sentences)   
  File "Loire/layout_generator/tools/../lib/modules/my_trainer.py", line 926, in sample_demo
    frames = env.batch_redraw(return_sequence=True)[0]
  File "Loire/layout_generator/tools/../lib/modules/layout_simulator.py", line 61, in batch_redraw
    frames = self.db.render_indices_as_output(self.scenes[i], return_sequence)
AttributeError: 'layout_coco_bert' object has no attribute 'render_indices_as_output'
```

I think there is no definitions of 'render_indices_as_output' or 'render_scenes_as_output'.
How should I fixed it?

**Comment by VickiCui** [comment]
您好，您的邮件我已经收到，我会第一时间处理。
